#!/bin/bash

# Make sure interface is up
ifdown wlan0
ifup wlan0

# Enable DNS forwarding
#sysctl -w net.ipv4.ip_forward=1

# Enable NAT
#iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE

# Start the Access Point
/usr/sbin/hostapd /etc/hostapd.conf
