#!/usr/bin/expect

set remotescript [lindex $argv 0];
set username [lindex $argv 1];
set servername [lindex $argv 2];
set password [lindex $argv 3];

set size_orig [match_max]
match_max 60000

spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o HostbasedAuthentication=no -q $username@$servername $remotescript

set pass "$password"
expect {
    password: {send "$pass\r"; exp_continue}
}

match_max $size_orig
